import os
import asyncio
from xiaoyi.workflow.dag import DagGraph, DagNode, NodeKind, EdgeKind
from xiaoyi.orchestrator import Orchestrator
from xiaoyi.core.config import Config

async def main():
    config = Config.builder() \
        .set("llm.provider", "openai") \
        .set("llm.model", "gpt-4o-mini") \
        .build()

    # Create a simple workflow: Research -> Summarize -> Output
    graph = DagGraph()

    # Node 1: Research
    research_node = DagNode(
        id="research",
        kind=NodeKind.LLM_CALL,
        config={
            "prompt": "Research the topic: {{topic}}",
            "model": "gpt-4o-mini",
            "temperature": 0.3,
        }
    )
    graph.add_node(research_node)

    # Node 2: Summarize
    summarize_node = DagNode(
        id="summarize",
        kind=NodeKind.LLM_CALL,
        config={
            "prompt": "Summarize the following research: {{research.output}}",
            "model": "gpt-4o-mini",
            "temperature": 0.5,
        }
    )
    graph.add_node(summarize_node)

    # Node 3: Format Output
    format_node = DagNode(
        id="format",
        kind=NodeKind.TRANSFORM,
        config={
            "template": "# Summary\n\n{{summarize.output}}\n\n---\n*Generated by Xiaoyi Workflow*",
        }
    )
    graph.add_node(format_node)

    # Connect nodes
    graph.add_edge("research", "summarize", EdgeKind.DATA)
    graph.add_edge("summarize", "format", EdgeKind.DATA)

    print(f"Workflow graph created with {graph.node_count()} nodes")
    print(f"Topological order: {graph.topological_order()}")

    # Create orchestrator and execute
    orchestrator = Orchestrator(config)

    input_data = {"topic": "Python async programming"}

    result = await orchestrator.execute(graph, input_data)

    print("\nWorkflow Result:")
    print(result)

if __name__ == "__main__":
    asyncio.run(main())