use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

/// Alert severity levels.
///
/// @brief Defines the severity level of an alert
/// @group Monitoring
/// @since 0.1.0
/// @author Miruamel
/// @see Alert
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlertSeverity {
    /// Information — non-critical, may be used for informational purposes.
    ///
    /// @brief Information severity level
    /// @since 0.1.0
    Info,
    /// Warning — indicates a potential issue that requires attention.
    ///
    /// @brief Warning severity level
    /// @since 0.1.0
    Warning,
    /// Critical — indicates a serious issue that requires immediate action.
    ///
    /// @brief Critical severity level
    /// @since 0.1.0
    Critical,
}

/// Represents a monitoring alert.
///
/// @brief A single alert generated by evaluating an [`crate::xiaoyi::monitoring::alerts::AlertRule`]
/// @group Monitoring
/// @since 0.1.0
/// @author Miruamel
/// @see AlertSeverity
/// @see AlertRule
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    /// Unique identifier for the alert.
    ///
    /// @brief Unique identifier
    pub id: String,
    /// Name of the rule that triggered this alert.
    ///
    /// @brief Name of the rule that generated the alert
    pub rule_name: String,
    /// Severity level of the alert.
    ///
    /// @brief Severity level of the alert
    pub severity: AlertSeverity,
    /// Human-readable description of the alert.
    ///
    /// @brief Description of the alert
    pub message: String,
    /// Unix timestamp (seconds since epoch) when the alert was generated.
    ///
    /// @brief Timestamp of alert creation (Unix epoch seconds)
    pub timestamp: u64,
    /// Whether the alert is currently active.
    ///
    /// @brief Indicates if the alert is currently firing
    pub is_active: bool,
}

impl Alert {
    /// Creates a new alert.
    ///
    /// @brief Construct a new alert
    /// @param id Unique identifier for the alert
    /// @param rule_name Name of the rule that generated the alert
    /// @param severity Severity level
    /// @param message Human-readable description
    /// @return New `Alert` instance
    /// @since 0.1.0
    pub fn new(
        id: String,
        rule_name: String,
        severity: AlertSeverity,
        message: String,
    ) -> Self {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        Self {
            id,
            rule_name,
            severity,
            message,
            timestamp,
            is_active: true,
        }
    }
}