use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::xiaoyi::monitoring::alerts::alert::{Alert, AlertSeverity};

/// Comparison operators for alert rule evaluation.
///
/// @brief Defines the comparison operator used to evaluate metric thresholds
/// @group Monitoring
/// @since 0.1.0
/// @author Miruamel
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Comparison {
    /// Greater than (>)
    ///
    /// @brief Metric must be greater than threshold
    /// @since 0.1.0
    Greater,
    /// Less than (<)
    ///
    /// @brief Metric must be less than threshold
    /// @since 0.1.0
    Less,
}

/// Alert rule that defines when an alert should be triggered.
///
/// @brief Evaluates a metric against a threshold to generate alerts
/// @group Monitoring
/// @since 0.1.0
/// @author Miruamel
/// @see Alert
/// @see Comparison
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlertRule {
    /// Name of the rule (unique identifier).
    ///
    /// @brief Name of the rule
    pub name: String,
    /// Metric name to monitor (e.g., "cpu_usage", "memory_pressure").
    ///
    /// @brief Metric name to monitor
    pub metric: String,
    /// Threshold value for the metric.
    ///
    /// @brief Threshold value for the metric
    pub threshold: f64,
    /// Comparison operator to apply between metric value and threshold.
    ///
    /// @brief Comparison operator
    pub comparison: Comparison,
    /// Severity level for alerts generated by this rule.
    ///
    /// @brief Alert severity level
    pub severity: AlertSeverity,
}

impl AlertRule {
    /// Evaluates the rule against a given metric value.
    ///
    /// @brief Evaluates metric value against threshold
    /// @param metric_value The current value of the metric
    /// @return `Some(Alert)` if the condition holds, `None` otherwise
    /// @since 0.1.0
    /// @see Comparison
    /// @see Alert
    pub fn evaluate(&self, metric_value: f64) -> Option<Alert> {
        let condition = match self.comparison {
            Comparison::Greater => metric_value > self.threshold,
            Comparison::Less => metric_value < self.threshold,
        };

        if condition {
            Some(Alert::new(
                format!("alert_{}", Uuid::new_v4()),
                self.name.clone(),
                self.severity,
                format!(
                    "Metric {} ({}) {} threshold {}",
                    self.metric,
                    metric_value,
                    match self.comparison {
                        Comparison::Greater => ">",
                        Comparison::Less => "<",
                    },
                    self.threshold,
                ),
            ))
        } else {
            None
        }
    }
}