import { DagGraph, DagNode, NodeKind, EdgeKind } from "xiaoyi-ts";
import { Orchestrator } from "xiaoyi-ts";
import { Config } from "xiaoyi-ts";

async function main() {
    const config = Config.builder()
        .set("llm.provider", "openai")
        .set("llm.model", "gpt-4o-mini")
        .build();

    // Create a simple workflow: Research -> Summarize -> Output
    const graph = new DagGraph();

    // Node 1: Research
    const researchNode = new DagNode(
        "research",
        NodeKind.LLM_CALL,
        {
            prompt: "Research the topic: {{topic}}",
            model: "gpt-4o-mini",
            temperature: 0.3,
        }
    );
    graph.addNode(researchNode);

    // Node 2: Summarize
    const summarizeNode = new DagNode(
        "summarize",
        NodeKind.LLM_CALL,
        {
            prompt: "Summarize the following research: {{research.output}}",
            model: "gpt-4o-mini",
            temperature: 0.5,
        }
    );
    graph.addNode(summarizeNode);

    // Node 3: Format Output
    const formatNode = new DagNode(
        "format",
        NodeKind.TRANSFORM,
        {
            template: "# Summary\n\n{{summarize.output}}\n\n---\n*Generated by Xiaoyi Workflow*",
        }
    );
    graph.addNode(formatNode);

    // Connect nodes
    graph.addEdge("research", "summarize", EdgeKind.DATA);
    graph.addEdge("summarize", "format", EdgeKind.DATA);

    console.log(`Workflow graph created with ${graph.nodeCount()} nodes`);
    console.log(`Topological order: ${graph.topologicalOrder()}`);

    // Create orchestrator and execute
    const orchestrator = new Orchestrator(config);

    const input = { topic: "TypeScript async programming" };

    const result = await orchestrator.execute(graph, input);

    console.log("\nWorkflow Result:");
    console.log(JSON.stringify(result, null, 2));
}

main().catch(console.error);