use xiaoyi::workflow::dag::{DagGraph, DagNode, NodeKind, EdgeKind};
use xiaoyi::orchestrator::Orchestrator;
use xiaoyi::Config;
use std::collections::HashMap;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let config = Config::builder()
        .set("llm.provider", "openai")
        .set("llm.model", "gpt-4o-mini")
        .build()?;

    // Create a simple workflow: Research -> Summarize -> Output
    let mut graph = DagGraph::new();

    // Node 1: Research
    let research_node = DagNode::new(
        "research",
        NodeKind::LlmCall,
        serde_json::json!({
            "prompt": "Research the topic: {{topic}}",
            "model": "gpt-4o-mini",
            "temperature": 0.3,
        }),
    );
    graph.add_node(research_node)?;

    // Node 2: Summarize
    let summarize_node = DagNode::new(
        "summarize",
        NodeKind::LlmCall,
        serde_json::json!({
            "prompt": "Summarize the following research: {{research.output}}",
            "model": "gpt-4o-mini",
            "temperature": 0.5,
        }),
    );
    graph.add_node(summarize_node)?;

    // Node 3: Format Output
    let format_node = DagNode::new(
        "format",
        NodeKind::Transform,
        serde_json::json!({
            "template": "# Summary\n\n{{summarize.output}}\n\n---\n*Generated by Xiaoyi Workflow*",
        }),
    );
    graph.add_node(format_node)?;

    // Connect nodes
    graph.add_edge("research", "summarize", EdgeKind::Data)?;
    graph.add_edge("summarize", "format", EdgeKind::Data)?;

    println!("Workflow graph created with {} nodes", graph.node_count());
    println!("Topological order: {:?}", graph.topological_order()?);

    // Create orchestrator and execute
    let orchestrator = Orchestrator::new(config);

    let mut input = HashMap::new();
    input.insert("topic".to_string(), serde_json::Value::String("Rust async programming".to_string()));

    let result = orchestrator.execute(graph, input).await?;

    println!("\nWorkflow Result:");
    println!("{}", serde_json::to_string_pretty(&result)?);

    Ok(())
}