use xiaoyi::{
    DagGraph, DagNode, DagEdge, NodeKind, EdgeKind, NodeId,
    Orchestrator, ConfigBuilder, AgentBuilder,
    EnvSource
};
use std::collections::HashMap;

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // Load configuration
    let config = ConfigBuilder::new()
        .add_source(EnvSource::new())
        .build()?;

    // Create a simple workflow: Research -> Summarize -> Output
    let mut graph = DagGraph::new();

    // Node 1: Research
    let mut research_metadata = HashMap::new();
    research_metadata.insert("prompt".to_string(), "Research the topic: {{topic}}".to_string());
    research_metadata.insert("model".to_string(), "gpt-4o-mini".to_string());
    research_metadata.insert("temperature".to_string(), "0.3".to_string());

    let research_node = DagNode::new(
        NodeId("research".to_string()),
        "Research".to_string(),
        NodeKind::Task,
    );
    graph.add_node(research_node);

    // Node 2: Summarize
    let mut summarize_metadata = HashMap::new();
    summarize_metadata.insert("prompt".to_string(), "Summarize the following research: {{research.output}}".to_string());
    summarize_metadata.insert("model".to_string(), "gpt-4o-mini".to_string());
    summarize_metadata.insert("temperature".to_string(), "0.5".to_string());

    let summarize_node = DagNode::new(
        NodeId("summarize".to_string()),
        "Summarize".to_string(),
        NodeKind::Task,
    );
    graph.add_node(summarize_node);

    // Node 3: Format Output (using Chain as a suitable kind)
    let mut format_metadata = HashMap::new();
    format_metadata.insert("template".to_string(), "# Summary\n\n{{summarize.output}}\n\n---\n*Generated by Xiaoyi Workflow*".to_string());

    let format_node = DagNode::new(
        NodeId("format".to_string()),
        "Format Output".to_string(),
        NodeKind::Chain,
    );
    graph.add_node(format_node);

    // Connect nodes
    let edge1 = DagEdge::new(
        NodeId("research".to_string()),
        NodeId("summarize".to_string()),
        EdgeKind::Sequential,
    );
    graph.add_edge(edge1).map_err(|e| anyhow::anyhow!("Failed to add edge research -> summarize: {}", e))?;

    let edge2 = DagEdge::new(
        NodeId("summarize".to_string()),
        NodeId("format".to_string()),
        EdgeKind::Sequential,
    );
    graph.add_edge(edge2).map_err(|e| anyhow::anyhow!("Failed to add edge summarize -> format: {}", e))?;

    println!("Workflow graph created with {} nodes", graph.node_count());
    
    let topo_order = graph.topological_order().map_err(|e| anyhow::anyhow!("Failed to get topological order: {}", e))?;
    println!("Topological order: {:?}", topo_order);

    // Create orchestrator and agent
    let orchestrator = Orchestrator::new(config.clone());
    let agent = AgentBuilder::new(config)
        .name("workflow-agent")
        .model("gpt-4o-mini")
        .build()?;

    // Run the agent (which would execute the workflow)
    orchestrator.run(agent).await?;

    println!("\nWorkflow setup complete. Agent is ready to execute the DAG.");

    Ok(())
}